import {StyleSheet} from 'react-native';

// eslint-disable-next-line no-undef
export default (styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  activityIndicator: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  section: {
    paddingTop: 12.8,
    paddingRight: 16,
    paddingBottom: 12.8,
    paddingLeft: 16,
  },
  image: {
    flex: 1,
    height: 20,
    width: 20,
    resizeMode: 'contain',
    marginTop: 18,
    position: 'absolute',
    right: 0,
  },
  productsSection: {
    color: '#224499',
    fontWeight: 'normal',
    fontFamily: 'BloomSpeakOT-Bold',
    fontSize: 20.48,
    padding: 0,
    margin: 0,
    lineHeight: 55,
  },
  billsSection: {
    color: '#224499',
    fontWeight: 'normal',
    fontFamily: 'BloomSpeakOT-Bold',
    fontSize: 20,
    lineHeight: 25,
  },
  para: {
    color: '#5c5c5c',
    fontSize: 16,
    fontFamily: 'BloomSpeakOT-Regular',
    margin: 0,
  },
  listSection: {
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderColor: 'rgb(204, 208, 218)',
  },
  list: {
    paddingTop: 9.6,
    paddingRight: 12.8,
    paddingBottom: 9.6,
    paddingLeft: 16,
    borderColor: 'rgb(204, 208, 218)',
    borderBottomWidth: 1,
    flex: 1,
    flexDirection: 'row',
  },
  listItem: {
    color: '#00aadd',
    fontSize: 20.8,
    fontFamily: 'BloomSpeakOT-Bold',
  },
  banner: {
    padding: 8,
  },
  promoheader: {
    paddingTop: 7,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 8,
    color: '#333333',
    fontFamily: 'BloomSpeakOT-Bold',
    fontSize: 20,
    lineHeight: 30,
  },
  promopara: {
    paddingTop: 3.5,
    paddingRight: 0,
    paddingBottom: 10.5,
    paddingLeft: 7.5,
    color: '#666666',
    fontFamily: 'BloomSpeakOT-Regular',
    fontSize: 15,
  },
  promobuttonouter1: {
    paddingTop: 12.5,
    paddingRight: 7.5,
    paddingBottom: 12.5,
    paddingLeft: 7.5,
  },
  promobuttonouter2: {
    alignItems: 'center',
    backgroundColor: '#16bae7',
    height: 40,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#00AADD',
    borderRadius: 2,
  },
  promobutton: {
    fontSize: 15,
    letterSpacing: 0.2,
    fontFamily: 'BloomSpeakOT-Bold',
    color: '#fff',
    shadowColor: '#1480a4',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.8,
    shadowRadius: 2,
  },
}));
